### ISSUE TITLE
Can't see the output image

### ISSUE THREAD

**Issue by ziudeso** [ValyrianTech/ComfyUI_with_Flux#1]
Hi, thanks for your awesome effort into putting this into a package!!
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/643ba111-2c0c-4991-97a5-7586d3b81886">

Performed all the steps correctly but not getting the output image after the processing, tried on multiple browsers.
Thanks in advance for your help

**Comment by WouterGlorieux** [comment]
Are you running this on Runpod.io? What GPU are you using?
I find it odd that the queue size says 'ERR', it is supposed to be 0. Then just clicking 'Queue Prompt' should start the generation.

**Comment by WouterGlorieux** [comment]
Maybe take a look at this: https://www.reddit.com/r/comfyui/comments/17oilpa/help_me_error_is_queue_sizeerr/

**Comment by ziudeso** [comment]
Hi, sorry the image isn't representative, these two are (using your default startup workflow):
![image](https://github.com/user-attachments/assets/1735f702-949b-44f3-8ff5-d6e4cfd0e8b3)
![image](https://github.com/user-attachments/assets/724125e9-7314-4c9c-af0c-5fc1d7048aee)

Tried on Chrome, Safari, Edge 

Maybe I'm missing something?

**Comment by WouterGlorieux** [comment]
I don't think it is an issue with your browser. Probably an issue with ComfyUI itself, have you tried deploying a new pod on Runpod? or restarting it?

**Comment by ziudeso** [comment]
Yeah tried even to recreating it 2 times

**Comment by WouterGlorieux** [comment]
Are you sure you are using runpod.io? Because I keep having this feeling you are not and you are trying to re-build the docker container from scratch yourself. You don't have to do that, www.runpod.io is a website where you can rent a GPU and deploy this container very easily with one click.
https://runpod.io/console/deploy?template=rzg5z3pls5&ref=2vdt3dn9

**Comment by ziudeso** [comment]
Well found the thing: 
Running from here (http) doesn't show the image
![image](https://github.com/user-attachments/assets/54da310e-3382-4a76-80f9-5feade44dac0)

Running from here (https) does
![image](https://github.com/user-attachments/assets/80edcbef-376d-4fc3-bc15-d999d79813ac)
