### ISSUE TITLE
Outpainting preview chooser blank

### ISSUE THREAD

**Issue by Tetsuo7945** [ValyrianTech/ComfyUI_with_Flux#10]
I'm not sure if I'm missing something, but the Outpainting workflow doesn't show a preview in the initial Control Panel group, no matter the image I have selected. I tried adjusting the x & y percentage sliders, and opened in a different web browser, no change.

![Clipboard_11-18-2024_01](https://github.com/user-attachments/assets/8c93fee8-1788-4ab0-af5e-077623ffb67b)

**Comment by WouterGlorieux** [comment]
That workflow requires a few additional models to be downloaded first, did you run the command 'bash /download_Outpainting.sh' in a terminal to download them?

**Comment by Tetsuo7945** [comment]
> That workflow requires a few additional models to be downloaded first, did you run the command 'bash /download_Outpainting.sh' in a terminal to download them?

yes

**Comment by WouterGlorieux** [comment]
hmm, not sure what the problem is then, are you getting any errors or messages in the logs? Are any of the nodes turning red when you click the 'Queue Prompt' button?
Also if I remember correctly, that preview doesn't show an image but rather a white rectangle on a black background to indicate the size and position of the original image in the outpainted image.

**Comment by Tetsuo7945** [comment]
When I queue prompt, the preview updates with the chosen image on a black background - but further changes to the sliders don't update any of the preview nodes. I'm assuming they're supposed to, so one has a guide to what they're getting in the output.

I found one error in my log, from startup, I suspect it's not relevant here - 
😺dzNodes: LayerStyle -> Cannot import name 'guidedFilter' from 'cv2.ximgproc'
A few nodes cannot works properly, while most nodes are not affected. Please REINSTALL package 'opencv-contrib-python'.
For detail refer to https://github.com/chflame163/ComfyUI_LayerStyle/issues/5

I tried one of the suggested solutions for that, and it cleared the error on restarting comfyui, but then there were further different issues with other packages, as a result.

**Comment by WouterGlorieux** [comment]
I'm not the original maker of the workflow, I just made a few changes to it so it would work with the rest of the template. I think that is just how the workflow works, it only updates the preview after you click the queue prompt button, it is not very user-friendly indeed, but you can use the switches in that workflow to disable the later parts of the workflow until you find the right settings for the sliders.

**Comment by Tetsuo7945** [comment]
Okay, I can work with that. Sorry for troubling you with my assumption. I appreciate your effort in putting all of this together!

**Comment by Tetsuo7945** [comment]
Okay, I can work with that. Sorry for troubling you with my assumption. I appreciate your effort in putting all of this together!
