### ISSUE TITLE
Authentication issues downloading with wget

### ISSUE THREAD

**Issue by OblivionState** [ValyrianTech/ComfyUI_with_Flux#12]
I have been having issues lately downloading any files via wget onto my server. When I download within either jupyter or the web terminal I get the error "Username/Password Authentication Failed". When I open web terminal I don't get prompted to enter the username or password that are provided. Is there a workaround for this?

**Comment by WouterGlorieux** [comment]
Is this something that used to work before? What files are you trying to wget? Do you mean the flux models?

**Comment by OblivionState** [comment]
It did work before, not sure what changed though as I was never prompted for the user and pass when accessing web terminal. Pretty much any files that I try to pull from github or hugging face. Here is one I am trying to download now, these screenshots are in both jupyter notebook and web term.

![f6b563f70345487e593a29e1314ac052](https://github.com/user-attachments/assets/c4bac663-6a4d-4134-9c1c-003f7eecc81c)
![ea2fd523bfc953e1abfb16b918d32423](https://github.com/user-attachments/assets/54e7ad5c-53e0-4943-ba37-01f28e2eaf25)

**Comment by WouterGlorieux** [comment]
The flux repo on huggingface is a gated repo, did you set the HF_TOKEN on the environment variables, and did you enable 'access to gated repos' on your huggingface token?

**Comment by OblivionState** [comment]
Yes, the env variable is set and when creating the token I did not see any specific option for gated repos but I believe it has write permissions. this is not something I had to do before, I still have the same issue even when trying to get files from Civitai so I don't think its a website authentication issue

**Comment by WouterGlorieux** [comment]
Try something like this:
wget -O "/ComfyUI/models/diffusion_models/flux1-dev.sft" --header="Authorization: Bearer ${HF_TOKEN}" "https://huggingface.co/black-forest-labs/FLUX.1-dev/resolve/main/flux1-dev.safetensors?download=true"

replace $(HF_TOKEN) with your actual token

**Comment by OblivionState** [comment]
That worked for me! Thank you
