### ISSUE TITLE
Request: Add a jupyter notebook

### ISSUE THREAD

**Issue by eyegeegeewhy** [ValyrianTech/ComfyUI_with_Flux#2]
Hi 
Firstly thankyou for creating this very simple run runpod template. Would it be possible to add a jupyter notebook to the template. I appreciate its not its primary focus but for people like me who are not great on the command line its an easy way to be able to upload/download files to the the pod and edit any config files i may need to. 

Cheers Jordan

**Comment by WouterGlorieux** [comment]
I'm planning to do an update of the template in a few days, I'll try to include a jupyter notebook as multiple people have asked me already.

**Comment by WouterGlorieux** [comment]
JupyterLab has been added for easy upload of files.
