### ISSUE TITLE
Not a bug, just a huge thank you.

### ISSUE THREAD

**Issue by alexc-hollywood** [ValyrianTech/ComfyUI_with_Flux#6]
This is a brilliant project and it's been immensely helpful learning all the pieces via Runpod with the UI set up - the model, ComfyUI, etc. It's probably taken a lot of time and i just wanted to share the love and appreciation for all the hours you've put in. You're a legend. Thank you.

Suggestion:

Any chance you could do the same for **CogVideoX I2V** as a Runpod template? Or make it part of the workflow? The implementations so far aren't great because of the latency, but it's a fascinating idea for cartoons and illustrations.

- https://huggingface.co/THUDM/CogVideoX-5b-I2V
- https://github.com/kijai/ComfyUI-CogVideoXWrapper (best so far)
- https://www.segmind.com/models/cog-video-5b-i2v (no guidance or config but reasonable output)
- https://replicate.com/thudm/cogvideox-i2v

I've tested this on Replicate (times out if the iterations are too high) and Segmind to date, and the latter takes 360s or so (at least) without any visual progress feedback.

**Comment by WouterGlorieux** [comment]
@alexc-hollywood Thank you for your kind words, I really appreciate it.

CogVideoX is actually on my list of things I want to test out, as soon as I find some time. I will need something to make animations for my own projects anyway, so thank you for the links. I will probably add it as another workflow when I get around to it.
